version: '3'
services:
  redis:
    image: redis:latest
  mongodb:
    image: bitnami/mongodb:latest
  web:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "80:7001"
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./src/:/usr/src/app/src/

